[package]
name = "anothersubatomo/moonslice"
version = "0.3.3"
description = "A simple, robust, and blazingly fast lexical analyzer generator in Luau"
license = "MIT"
authors = ["AnotherSubatomo"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
